import type { UnifiedPost, AISummaryData, PlatformHeat } from "./types";

export function generateMockPosts(query: string): UnifiedPost[] {
  const now = new Date();
  const posts: UnifiedPost[] = [
    // Reddit posts
    {
      id: "reddit-1",
      platform: "reddit",
      authorName: "CodeWizard42",
      authorAvatar: null,
      authorHandle: "u/CodeWizard42",
      content: `Just had a fascinating discussion about "${query}" at work. The consensus among senior devs is that this is going to fundamentally change how we approach software engineering. Here's my detailed breakdown of the key arguments...`,
      url: "https://reddit.com/r/programming/comments/abc123",
      timestamp: new Date(now.getTime() - 2 * 3600000).toISOString(),
      engagement: { likes: 2847, comments: 342, shares: 156, views: 45200 },
      sentiment: "positive",
      relevanceScore: 0.95,
    },
    {
      id: "reddit-2",
      platform: "reddit",
      authorName: "TechSkeptic",
      authorAvatar: null,
      authorHandle: "u/TechSkeptic",
      content: `Hot take: "${query}" is massively overhyped. I've been in this industry for 15 years and I've seen at least 5 cycles like this. The real question isn't whether it works, but whether the economics make sense long-term.`,
      url: "https://reddit.com/r/technology/comments/def456",
      timestamp: new Date(now.getTime() - 4 * 3600000).toISOString(),
      engagement: { likes: 1523, comments: 891, shares: 234 },
      sentiment: "negative",
      relevanceScore: 0.88,
    },
    {
      id: "reddit-3",
      platform: "reddit",
      authorName: "DataDrivenDev",
      authorAvatar: null,
      authorHandle: "u/DataDrivenDev",
      content: `I ran a comprehensive analysis on "${query}" - pulled data from 50+ sources, surveyed 200 professionals. Results are surprising: 67% see it as transformative, but only 23% have actually implemented it. Full methodology in comments.`,
      url: "https://reddit.com/r/datascience/comments/ghi789",
      timestamp: new Date(now.getTime() - 6 * 3600000).toISOString(),
      engagement: { likes: 4521, comments: 567, shares: 890 },
      mediaType: "link",
      sentiment: "neutral",
      relevanceScore: 0.92,
    },
    // X/Twitter posts
    {
      id: "x-1",
      platform: "x",
      authorName: "Sarah Chen",
      authorAvatar: null,
      authorHandle: "@sarahchen_tech",
      content: `The conversation around "${query}" is hitting a tipping point. Every major tech CEO I've spoken to this week has mentioned it unprompted. This isn't hype anymore — it's strategy. 🧵`,
      url: "https://x.com/sarahchen_tech/status/123456",
      timestamp: new Date(now.getTime() - 1 * 3600000).toISOString(),
      engagement: { likes: 12400, comments: 1890, shares: 4500, views: 890000 },
      sentiment: "positive",
      relevanceScore: 0.97,
    },
    {
      id: "x-2",
      platform: "x",
      authorName: "Marcus Webb",
      authorAvatar: null,
      authorHandle: "@marcuswebb",
      content: `Unpopular opinion: "${query}" will create MORE jobs than it destroys. But they'll be different jobs, requiring different skills. The transition will be painful for some, liberating for others.`,
      url: "https://x.com/marcuswebb/status/789012",
      timestamp: new Date(now.getTime() - 3 * 3600000).toISOString(),
      engagement: { likes: 8934, comments: 2341, shares: 3120, views: 567000 },
      sentiment: "mixed",
      relevanceScore: 0.91,
    },
    {
      id: "x-3",
      platform: "x",
      authorName: "Dev Community",
      authorAvatar: null,
      authorHandle: "@devcomm",
      content: `Poll: How do you feel about "${query}"?\n\n🟢 Excited - 45%\n🟡 Cautiously optimistic - 30%\n🔴 Concerned - 15%\n⚪ Don't care - 10%\n\n23,456 votes · 2 hours left`,
      url: "https://x.com/devcomm/status/345678",
      timestamp: new Date(now.getTime() - 5 * 3600000).toISOString(),
      engagement: { likes: 5600, comments: 890, shares: 1200, views: 234000 },
      sentiment: "neutral",
      relevanceScore: 0.85,
    },
    // YouTube posts
    {
      id: "yt-1",
      platform: "youtube",
      authorName: "TechInsights Daily",
      authorAvatar: null,
      authorHandle: "@techinsightsdaily",
      content: `"${query}" - The Complete 2025 Breakdown | What You Need To Know`,
      url: "https://youtube.com/watch?v=abc123",
      timestamp: new Date(now.getTime() - 8 * 3600000).toISOString(),
      engagement: { likes: 34500, comments: 2890, shares: 5600, views: 1200000 },
      mediaType: "video",
      sentiment: "positive",
      relevanceScore: 0.93,
    },
    {
      id: "yt-2",
      platform: "youtube",
      authorName: "The Pragmatic Engineer",
      authorAvatar: null,
      authorHandle: "@pragmaticeng",
      content: `Why "${query}" changes everything for software engineers — and what to do about it`,
      url: "https://youtube.com/watch?v=def456",
      timestamp: new Date(now.getTime() - 12 * 3600000).toISOString(),
      engagement: { likes: 21000, comments: 1567, shares: 3400, views: 780000 },
      mediaType: "video",
      sentiment: "neutral",
      relevanceScore: 0.89,
    },
    // Medium posts
    {
      id: "medium-1",
      platform: "medium",
      authorName: "Alexandra Rivera",
      authorAvatar: null,
      authorHandle: "@arivera",
      content: `I spent 6 months researching "${query}" and here are my findings. This deep dive covers the technical, economic, and social implications that most articles overlook. A 15-minute read that could change your perspective.`,
      url: "https://medium.com/@arivera/deep-dive",
      timestamp: new Date(now.getTime() - 24 * 3600000).toISOString(),
      engagement: { likes: 8900, comments: 234, shares: 1200 },
      sentiment: "positive",
      relevanceScore: 0.90,
    },
    {
      id: "medium-2",
      platform: "medium",
      authorName: "James Park",
      authorAvatar: null,
      authorHandle: "@jpark_writes",
      content: `The contrarian case against "${query}": Why the skeptics might be right this time. Drawing from historical parallels and economic data, I argue we're in a classic hype bubble.`,
      url: "https://medium.com/@jpark_writes/contrarian-case",
      timestamp: new Date(now.getTime() - 48 * 3600000).toISOString(),
      engagement: { likes: 5600, comments: 456, shares: 890 },
      sentiment: "negative",
      relevanceScore: 0.86,
    },
    },
  ];

  return posts.sort((a, b) => b.relevanceScore - a.relevanceScore);
}

export function generateMockAISummary(query: string): AISummaryData {
  return {
    overallSummary: `The discussion around "${query}" is highly active across multiple platforms with a predominantly positive but nuanced sentiment. Technical communities on Reddit are focused on practical implementation challenges, while X/Twitter discourse centers on broader societal implications. Medium contributors provide deep-dive analyses with contrarian perspectives gaining traction. Overall, there's a clear divide between practitioners who see immediate value and observers who urge caution about long-term consequences.`,
    keyOpinions: [
      "Senior engineers see transformative potential but emphasize the need for responsible implementation",
      "Industry analysts predict significant job market restructuring within 2-3 years",
      "Academic researchers highlight gaps between marketing claims and actual capabilities",
      "Startup founders report accelerating enterprise adoption rates",
      "Skeptics draw parallels to previous hype cycles, warning of a potential correction",
    ],
    trendingNarratives: [
      "The productivity paradox: more tools, same output?",
      "Open-source alternatives gaining ground on commercial solutions",
      "Regulatory frameworks struggling to keep pace with innovation",
      "Skills gap widening between early adopters and traditional practitioners",
    ],
    sentimentBreakdown: {
      positive: 52,
      negative: 23,
      neutral: 25,
    },
    controversialTakes: [
      '"This will eliminate 80% of junior developer roles within 5 years" — sparked heated debate across all platforms',
      '"Companies investing heavily now are making the same mistakes as the dot-com era" — contrarian view gaining followers',
      '"The real winners will be those who resist the hype and focus on fundamentals" — resonating with experienced professionals',
    ],
  };
}

export function generateMockPlatformHeat(query: string): PlatformHeat[] {
  return [
    { platform: "x", count: 15234, intensity: 5 },
    { platform: "reddit", count: 8901, intensity: 4 },
    { platform: "youtube", count: 2100, intensity: 3 },
    { platform: "medium", count: 1200, intensity: 2 },
    { platform: "linkedin", count: 890, intensity: 1 },
    { platform: "threads", count: 456, intensity: 1 },
    { platform: "instagram", count: 234, intensity: 1 },
    { platform: "tiktok", count: 123, intensity: 1 },
    { platform: "facebook", count: 89, intensity: 1 },
  ];
}
